### ISSUE TITLE
Simplify README documentation

### ISSUE THREAD

**Issue by dimberman** [astro-projects/astro#101]
Acceptance criteria:
* User should be able to read README page in two minutes
* Documentation should follow the guidelines outlined here 

https://documentation.divio.com/
https://www.youtube.com/watch?v=t4vKPhjcMZg
https://diataxis.fr/

**Comment by tatiana** [comment]
I pushed the changes to the README - still working on them:
https://github.com/astro-projects/astro/tree/readme

**Comment by tatiana** [comment]
Ready for review: https://github.com/astro-projects/astro/pull/157
