### ISSUE TITLE
Dataframe tasks not inheriting connection ID in 0.5.1

### ISSUE THREAD

**Issue by kentdanas** [astro-projects/astro#134]
**Context**

As of 0.5.1, `dataframe` tasks are not inheriting connection IDs from upstream tasks. `dataframe` tasks with or without an output table currently fail with:

```raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `None` isn't defined```

Possibly related to https://github.com/astro-projects/astro/issues/117

**Desired Behavior**

`dataframe` tasks should inherit the connection ID from an upstream task if there is one.

**Comment by tatiana** [comment]
@kentdanas Thank you very much for reporting this issue. @dimberman already identified the problem and we will soon have a fix. In the meantime, we'll yank the 0.5.2 release. If possible, please, stick to the previous releases.

**Comment by dimberman** [comment]
Addressed at the same time as #124
