### ISSUE TITLE
Refactor tests which rely on pre-populated Snowflake database

### ISSUE THREAD

**Issue by tatiana** [astro-projects/astro#136]
**Context**
At the moment (Astro 0.5.2), some Snowflake tests run using a specific table (`ADOPTION_CENTER_1`), which was pre-populated in the past. Recently there was a Snowflake migration which made our CI break because the table was not available in the new schema:
https://github.com/astro-projects/astro/runs/5308330863?check_suite_focus=true

**Acceptance criteria**
* All Snowflake tests should be self-contained. If they rely on previous data, we should define (`pytest`) fixtures or setup/teardown methods. The setup step would load the dataset into the desired Snowflake table, and the teardown would delete the table.

**Comment by dimberman** [comment]
This ticket may be addressed by #139. The simplest solution to just not use adoption center data

**Comment by tatiana** [comment]
We were able to fetch from a legacy Snowflake DB the fixtures which are still used by legacy tests:

Adoption center 1
```
"2021-01-01","Dog","Stanley","3"                                                
"2021-01-01","Dog","Barney","6"
"2021-02-01","Cat","Whiskers","10"
"2021-03-01","Dog","Lila","1"
"2021-03-01","Dog","Toby","5"
"2021-04-01","Cat","Gretchen","4"
"2021-05-01","Guinea Pig","Maverick","11"
"2021-06-01","Cat","Pie","8"
"2021-07-01","Dog","Butter","12"
"2021-08-01","Dog","Peanut","2"
"2021-03-01","Cat","Fluffy","3"
"2021-04-01","Dog","Tobias","1"
"2021-04-01","Dog","Buddy","1"
"2021-04-01","Cat","Roo","2"
"2021-05-01","Guinea Pig","Piglet","2"
"2021-05-01","Cat","Ghost","3"
"2021-06-01","Dog","Ollie","4"
"2021-06-01","Dog","Eta","12"
```

And Adoption center 2
```
"2021-05-01","Cat","Dancer","3"                                                 
"2021-07-01","Dog","Prancer","1"
"2021-08-01","Dog","Comet","1"
"2021-09-01","Cat","Cupid","2"
"2021-10-01","Guinea Pig","Rudolph","4"
"2021-11-01","Cat","Spider","3"
"2021-12-01","Dog","Dasher","4"
"2021-10-01","Dog","Ettie","12"
```

**Comment by kaxil** [comment]
Is this still an issue?

**Comment by utkarsharma2** [comment]
One of the example dag uses this table - example_amazon_s3_snowflake_transform.py
