### ISSUE TITLE
Failing tests on CI on the main branch

### ISSUE THREAD

**Issue by tatiana** [astro-projects/astro#199]
**Context**

Between 16 hours ago and now there was some change in one of the unpinned dependencies of Astro and/or its test use (directly or indirectly). This caused tests that were passing before, to stop working when we retriggered the CI build. This is causing all the open PRs to fail as well.

**Acceptance criteria**
* Get `main` branch back to green

**Comment by tatiana** [comment]
I compared a virtualenv when tests were passing and another one built today, and some of the dependencies which changed and could justify the change of behaviour are:
* `apache-airflow-providers-google==6.5.0` (before: `apache-airflow-providers-google==6.4.0 `)
* `db-dtypes==0.3.1` (new)
* `google-cloud-bigquery==2.34.2` (was `google-cloud-bigquery==2.34.1`)
* `google-cloud-bigquery-datatransfer==3.6.1` (was `google-cloud-bigquery-datatransfer==3.6.0`)
* `pandas-gbq==0.17.3` (was `pandas-gbq==0.14.1`)

After having a quick look at `pandas-gbq`, it seems from 0.16 -> 0.17 they changed the casting of integers, which explains the issue we experienced:
https://github.com/googleapis/python-bigquery-pandas/commit/89078f89478469aa60a0a8b8e1e0c4a59aa059e0

**Comment by tatiana** [comment]
It seems `apache-airflow-providers-google==6.5.0` is the one that is responsible for Astro's dependency on `pandas-gbq`:
https://github.com/apache/airflow/blob/828d1cba4d9b85a166debdd8a8dfe363935c22cd/setup.py#L357

@kaxil @ashb it feels this was a breaking change (how values are cast), introduced in minor releases. We'll stop loading data to BQ using this pattern in the short term, so don't think it is a major issue to Astro itself - but I wonder if this could affect other Airflow users.

**Comment by ashb** [comment]
I think this will be unlikely to be noticed by many (changing one Int64 column type to another) as _I think_ it won't affect any processing, just the tests like the ones we have.

**Comment by tatiana** [comment]
That's reasonable, @ashb . Thanks a lot for checking it out!
