### ISSUE TITLE
Improve documentation for new joiners

### ISSUE THREAD

**Issue by tatiana** [astro-projects/astro#214]
**Context**

Recently, we had a new contributor (@bhavaniravi ), and we noticed parts of the documentation could improve.

We have a separate ticket to automate these steps: #214.

**Acceptance criteria**
* [ ] Update the [DEVELOPMENT docs](https://github.com/astro-projects/astro/blob/main/docs/DEVELOPMENT.md), so they are compatible with the strategy
* [x] The [CONTRIBUTING.md](https://github.com/astro-projects/astro/blob/main/docs/CONTRIBUTING.md) guidelines should either refer to [DEVELOPMENT.md](https://github.com/astro-projects/astro/blob/main/docs/DEVELOPMENT.md) or they should have the details embedded to them.

**Comment by kaxil** [comment]
closed by https://github.com/astro-projects/astro/pull/238
