### ISSUE TITLE
Add TypeHints

### ISSUE THREAD

**Issue by kaxil** [astro-projects/astro#281]
Make sure all the methods and functions within the following packages have typehints:
```
├── astro
│   ├── __init__.py
│   ├── constants.py
│   ├── dataframe
│   │   └── __init__.py

^^^ part 1

│   ├── settings.py
│   ├── sql
│   │   ├── __init__.py
│   │   ├── operators
│   │   │   ├── agnostic_aggregate_check.py
│   │   │   ├── agnostic_boolean_check.py

^^^ part 2

│   │   │   ├── agnostic_load_file.py
│   │   │   ├── agnostic_save_file.py
│   │   │   ├── agnostic_sql_append.py
│   │   │   ├── agnostic_sql_merge.py

^^^ part 3

│   │   │   ├── agnostic_sql_truncate.py
│   │   │   ├── agnostic_stats_check.py
│   │   │   ├── __init__.py
│   │   │   ├── sql_dataframe.py
│   │   │   └── sql_decorator.py

^^^ part 4

│   │   ├── parsers
│   │   │   ├── __init__.py
│   │   │   └── sql_directory_parser.py
│   │   └── table.py

^^^ part 5

│   └── utils
│       ├── bigquery_merge_func.py
│       ├── cloud_storage_creds.py
│       ├── database.py
│       ├── delete.py
│       ├── dependencies.py
│       ├── file.py

^^^ part 6

│       ├── __init__.py
│       ├── load.py
│       ├── path.py
│       ├── postgres_merge_func.py
│       ├── postgres_transform.py

^^^ part 7

│       ├── schema_util.py
│       ├── snowflake_append.py
│       ├── snowflake_merge_func.py
│       ├── snowflake_transform.py

^^^ part 8

│       ├── sqlite_merge_func.py
│       ├── table_handler.py
│       └── task_id_helper.py
https://github.com/astro-projects/astro/blob/main/tests/operators/utils.py

^^^ part 9
```
We'll be addressing this ticket in multiple PRs, so it is easy to review the work:

- [ ] Part 1 @utkarsharma2 
- [x] Part 2 @tatiana 
- [ ] Part 3 @utkarsharma2 
- [ ] Part 4 @tatiana 
- [ ] Part 5 @utkarsharma2 
- [ ] Part 6 @tatiana 
- [ ] Part 7 @utkarsharma2 
- [ ] Part 8 @tatiana 
- [ ] Part 9 @utkarsharma2

**Comment by tatiana** [comment]
@kaxil @utkarsharma2 do we want to cover tests with type hints as well? Or are we happy with this as a starting point?

**Comment by kaxil** [comment]
I would say: Ignore tests, for now, we can add it optionally but shouldn't enforce type hints for `tests`

**Comment by kaxil** [comment]
@utkarsharma2 @tatiana You can see the failing Type Checks in https://github.com/astro-projects/astro/runs/5859791874?check_suite_focus=true

**Comment by tatiana** [comment]
@kaxil @utkarsharma2 I adopted an alternative way of running MyPy locally and in the CI, so it is consistent and allows us to have the CI covering our work as we progress the implementation of type hints per part (group of files):
https://github.com/astro-projects/astro/pull/296

By the end of this ticket, we can remove the `files` section and just run MyPy against the entire `astro` module.

**Comment by kaxil** [comment]
Awesome, looks great

**Comment by kaxil** [comment]
Closing this in favor of https://github.com/astro-projects/astro/issues/279 . We will add TypeHints while refactoring modules
