### ISSUE TITLE
Refactor BaseDatabase and SqliteDatabase to use File

### ISSUE THREAD

**Issue by tatiana** [astro-projects/astro#330]
**Describe the context**
This task is part of the [Astro Python SDK refactor]().

**Dependencies**
* Depends on: #336

**Acceptance criteria**
* [ ] Refactor `BaseDatabase.export_table_to_file` and `BaseDatabase.load_file_to_table` to use an instance of the `File` class
* [ ] Refactor `SqliteDatabase.export_table_to_file` and `SqliteDatabase.load_file_to_table` to use an instance of the `File` class
* [ ] All the quality checks passed
* [ ] All the functions have typehints
* [ ] All the new functions and modules have docstrings
* [ ] The introduced code has 100% of test coverage

**Comment by utkarsharma2** [comment]
Closed by - https://github.com/astro-projects/astro/pull/356
