### ISSUE TITLE
load_file from multiple files [matching a pattern] in a directory

### ISSUE THREAD

**Issue by dimberman** [astro-projects/astro#78]
Acceptance criteria:
- A user should be able to point to a list of files via a regex pattern, and all of those files can be loaded into a single SQL database
- We will not handle merge conflicts. If there are multiple entries with the same key, we will surface the error when it is created.
- does not require new API, should just work if a user supplies a regex pattern to load_file
- notify @guohui-gao when this feature is ready

**Comment by dimberman** [comment]
@tatiana I started looking into this one a bit and I wonder if this isn't potentially a can of worms. I think s3 has support for something like this but I'm not sure it's universal. Have you done anything like this in the past?

**Comment by tatiana** [comment]
@dimberman, I suggest simplifying the problem from matching a regex to matching a prefix.
I firmly believe that will be enough.

With Airflow, I used:
* [S3Hook.list_prefixes](https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/_api/airflow/providers/amazon/aws/hooks/s3/index.html#airflow.providers.amazon.aws.hooks.s3.S3Hook.list_prefixes)
* [GoogleCloudStorageHoook.list](https://airflow.apache.org/docs/apache-airflow/1.10.6/_api/airflow/contrib/hooks/gcs_hook/index.html#airflow.contrib.hooks.gcs_hook.GoogleCloudStorageHook.list)

In the case of performing this operation locally, I've used:
* [glob](https://docs.python.org/3/library/glob.html) in the past

This pattern of matching prefixes is also prevalent in Apache Beam, an example:
* https://beam.apache.org/releases/pydoc/2.6.0/apache_beam.io.textio.html

**Comment by tatiana** [comment]
@utkarsharma2 @dimberman what do you think about renaming `load_file` to `load` and `save_file` to `save` as part of this ticket?

We had agreed on this in the past:
https://astronomer.slack.com/archives/C02B8SPT93K/p1644932836396039

And it would particularly make sense since we'll be supporting reading multiple files.
